# Generated by Django 5.0.6 on 2024-07-24 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('buybook', '0004_language_rename_order_date_order_ordered_at_and_more'),
        ('sellbook', '0004_language_alter_category_name_sellbook_delete_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.ManyToManyField(blank=True, related_name='user_orders', to='buybook.order')),
                ('past_events', models.ManyToManyField(blank=True, related_name='past_events', to='activity.event')),
                ('sold_books', models.ManyToManyField(blank=True, related_name='sold_books', to='sellbook.sellbook')),
                ('upcoming_events', models.ManyToManyField(blank=True, related_name='upcoming_events', to='activity.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
