# Generated by Django 5.0.6 on 2024-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_orders'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='orders', to='payment.paymentorder'),
        ),
    ]
