# Generated by Django 5.0.6 on 2024-07-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbook', '0004_language_alter_category_name_sellbook_delete_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellbook',
            name='booklang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sellbook.language'),
        ),
        migrations.AlterField(
            model_name='sellbook',
            name='booktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sellbook.category'),
        ),
    ]
