# Generated by Django 5.0.6 on 2024-07-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellbook', '0005_alter_sellbook_booklang_alter_sellbook_booktype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Languages'},
        ),
    ]
