# Generated by Django 5.0.6 on 2024-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybook', '0002_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
