# Generated by Django 5.0.6 on 2024-07-24 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buybook', '0004_language_rename_order_date_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buybook',
            name='booklang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buybook.language'),
        ),
        migrations.AlterField(
            model_name='buybook',
            name='booktype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buybook.category'),
        ),
    ]
